### ISSUE TITLE
What about list with 2 fields? Am I missing something sir?

### ISSUE THREAD

**Issue by fewbackseven** [jamesmontemagno/App4#1]
![Listwith2_fields2](https://user-images.githubusercontent.com/10475014/135726291-a3ece8f2-8530-4262-8cd8-1d575b23501a.jpg)
![Listwith2_fields](https://user-images.githubusercontent.com/10475014/135726295-0b772bdc-b2e5-4706-a45f-207732fcc3a8.jpg)

.
Why cant I bind fields of a class?

**Comment by jamesmontemagno** [comment]
This is because you didn't give your property a { get; set;} so the binding has no way of getting the value back. They are just public fields, you also have a typo in your XAML there as it should be "Details" not "Detail"

```csharp
public partial class MainPage : ContentPage
    {
        public List<Customer> MyList { get; set; }
        public MainPage()
        {
            InitializeComponent();
            MyList = new List<Customer>
            {
                new Customer { Name = "James", Details = "James Details"},
                new Customer { Name = "Harshith", Details = "Harshith Details"}

            };
            BindingContext = this;
        }
    }

    public class Customer
    {
        public string Name { get; set; }
        public string Details { get; set; }
    }
```

```xaml
<ListView ItemsSource="{Binding MyList}">
            <ListView.ItemTemplate>
                <DataTemplate>
                    <TextCell Text="{Binding Name}" TextColor="Orange"
                              Detail="{Binding Details}" DetailColor="Orange"/>
                </DataTemplate>
            </ListView.ItemTemplate>
        </ListView>
```

I pushed these changes to the rep so you can see them.

Please watch my 101 video on data binding https://www.youtube.com/watch?v=Pso1MeX_HvI and probably actually watch my full 101 series https://www.youtube.com/playlist?list=PLwOF5UVsZWUiHY1CkRVjYJ6dm0iCvAlfw

<img width="474" alt="Screen Shot 2021-10-02 at 9 15 06 PM" src="https://user-images.githubusercontent.com/1676321/135739503-0713e20e-48cb-4138-a051-5a4a6540cde9.png">

**Comment by fewbackseven** [comment]
I have uploaded broken project in a repo.  In this project the issue still persists. Please have a look at it once. I was learning PRISM and I just drag and dropped this LISTVIEW from their TOOLBOX. 
[https://github.com/fewbackseven/listView](url)

**Comment by jamesmontemagno** [comment]
@fewbackseven  I think you made it the repo private, can you make it public for me.

**Comment by fewbackseven** [comment]
> @fewbackseven  I think you made it the repo private, can you make it public for me.

Oops!🤦 Sorry.. I have made it public.. 👍

**Comment by jamesmontemagno** [comment]
See my PR to your project and why it isn't showing up because of CompiledBindings -> https://www.youtube.com/watch?v=3-cT97sBmxM

**Comment by jamesmontemagno** [comment]
Added info to https://stackoverflow.com/questions/69402029/it-seems-xamarin-listview-binding-is-broken-in-updated-vs-2019-16-11-3-collecti as well
